name: moslem
description: An app for all moslems
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  get: ^4.6.1
  uuid: 3.0.5
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
  fonts:
    - family: OpenSans
      fonts:
        - asset: asset/font/OpenSans-Regular.ttf

        - asset: asset/font/OpenSans-Italic.ttf
          style: italic

        - asset: asset/font/OpenSans-SemiBold.ttf
          weight: 600

        - asset: asset/font/OpenSans-SemiBoldItalic.ttf
          style: italic
          weight: 600

    # - family: AppIcon
    #   fonts:
    #     - asset: asset/font/app_icon.ttf
